version: "3.8"
services:
  database:
    image: tigranargit/database:latest
    environment:
      - MYSQL_ROOT_PASSWORD=QAproject21
      - MYSQL_DATABASE=dnd-database
  frontend:
    image: tigranargit/frontend:latest
    depends_on:
      - database
      - backend
      - service1
      - service2
    environment:
      - MYSQL_USER=tigran@dnd-database
      - MYSQL_PWD=QAproject21
      - MYSQL_IP=dnd-database.mysql.database.azure.com
      - MYSQL_DB=dnd-database
      - MYSQL_SK=sdlkfjsdfkj
    ports:
    - target: 5000
      published: 5000
  backend:
    image: tigranargit/backend:latest
    ports:
    - target: 5003
    - published: 5003
  service1:
    image: tigranargit/service1:latest
    ports:
    - target: 5001
    - published: 5001
  service2:
    image: tigranargit/service2:latest
    ports:
    - target: 5002
    - published: 5002
  nginx:
    image: tigranargit/nginx:latest
    depends_on:
      - frontend
    ports:
    - target: 80
      published: 80
      protocol: tcp